# Generated by Django 4.2.4 on 2023-08-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='updated_at',
        ),
    ]
