# Generated by Django 4.2.4 on 2023-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cakes/')),
                ('date', models.DateField(auto_now_add=True)),
                ('mt', models.CharField(max_length=100)),
                ('author', models.CharField(default='author name', max_length=100)),
            ],
        ),
    ]
